### ISSUE TITLE
Deserialization of PlaceType is not invertible.

### ISSUE THREAD

**Issue by adamnemecek** [leontoeides/google_maps#13]
This code does not work.

```rust
use google_maps::prelude::PlaceType;
let z: PlaceType = serde_json::from_str(&serde_json::to_string(&PlaceType::Accounting).unwrap()).unwrap();
```

**Comment by leontoeides** [comment]
I'd argue that's a quirk of Rust. `String::from(my_string)` and `my_string.to_string()` are not the same.

I implemented `Display` (intended for end-users, terminal output) for these types. The `to_string()` function uses the `Display` implementation to convert the enumeration into a string.

However, I've implemented `String::from` for these types. This will give the "code" you're looking for. I haven't tried this, but try using `String::from(&PlaceType::Accounting)` rather than `serde_json::to_string(&PlaceType::Accounting).unwrap()`

**Comment by leontoeides** [comment]
Just a note that I came around on this issue and this has been fixed.
